name: SoGoodTea Weekly Promotion

on:
  schedule:
    - cron: '0 9 * * 1'
  workflow_dispatch:

jobs:
  trigger-dify:
    runs-on: ubuntu-latest
    
    steps:
    - name: Call Dify Workflow API
      id: dify
      run: |
        # 直接调用Dify API并检查响应
        response=$(curl -s -X POST "https://api.dify.ai/v1/workflows/8e8aa058-7d7e-4f20-bfdb-8725c7e3edef/run" \
        -H "Authorization: Bearer ${{ secrets.DIFY_API_KEY }}" \
        -H "Content-Type: application/json" \
        -d '{
          "inputs": {
            "week_number": 1,
            "target_languages": "英语,德语,法语",
            "platforms": "Facebook,Instagram,Twitter"
          },
          "user": "fengzheng9@icloud.com",
          "response_mode": "blocking"
        }')
        
        echo "Dify Response: $response"
        
        # 检查是否成功
        if echo "$response" | grep -q '"code"'; then
          echo "Dify API returned error: $response"
          exit 1
        fi
        
        # 保存响应到文件
        echo "$response" > dify_response.json

    - name: Extract Content
      id: extract
      run: |
        # 使用Python解析JSON，避免jq语法问题
        python3 << 'EOF'
import json
import sys

try:
    with open('dify_response.json', 'r') as f:
        data = json.load(f)
    
    # 提取内容
    content_result = data.get('data', {}).get('outputs', {}).get('content_result', '')
    image_url = data.get('data', {}).get('outputs', {}).get('generated_images', [{}])[0].get('url', '')
    
    # 提取英语内容
    if content_result and isinstance(content_result, dict):
        english_content = content_result.get('content_by_language', {}).get('英语', {}).get('Facebook/Instagram', '')
    else:
        english_content = ''
    
    # 输出到GitHub Actions
    with open('$GITHUB_OUTPUT', 'a') as f:
        f.write(f'content_result={content_result}\n')
        f.write(f'image_url={image_url}\n')
        f.write(f'english_content={english_content}\n')
        
    print(f"Content extracted successfully")
    print(f"English content: {english_content}")
    print(f"Image URL: {image_url}")
    
except Exception as e:
    print(f"Error parsing response: {e}")
    sys.exit(1)
EOF

    - name: Post to Facebook
      run: |
        # 检查是否有有效内容
        if [ -z "${{ steps.extract.outputs.english_content }}" ]; then
          echo "No valid content to post to Facebook"
          exit 0
        fi
        
        # 发布文字内容
        curl -X POST "https://graph.facebook.com/v18.0/${{ secrets.FACEBOOK_PAGE_ID }}/feed" \
        -H "Authorization: Bearer ${{ secrets.FACEBOOK_ACCESS_TOKEN }}" \
        -H "Content-Type: application/json" \
        -d '{
          "message": "${{ steps.extract.outputs.english_content }}"
        }'
        
        # 发布图片（如果有）
        if [ -n "${{ steps.extract.outputs.image_url }}" ]; then
          curl -X POST "https://graph.facebook.com/v18.0/${{ secrets.FACEBOOK_PAGE_ID }}/photos" \
          -H "Authorization: Bearer ${{ secrets.FACEBOOK_ACCESS_TOKEN }}" \
          -F "url=${{ steps.extract.outputs.image_url }}" \
          -F "message=${{ steps.extract.outputs.english_content }}"
        fi

    - name: Log Results
      run: |
        echo "Content posted to Facebook successfully!"
        echo "English content: ${{ steps.extract.outputs.english_content }}"
        echo "Image URL: ${{ steps.extract.outputs.image_url }}"
